#include "word_bear_words.h"

#include <stddef.h>

#define W(word_text, part_text, meaning_text, example_text) \
    { word_text, part_text, meaning_text, example_text }

static const word_bear_word_t WORDS[WORD_BEAR_WORD_COUNT] = {
    W("curious",  "adj.",  "好奇的",       "Curious minds ask questions."),
    W("focus",    "v./n.", "专注；集中",   "Focus on one thing at a time."),
    W("improve",  "v.",    "改善；提高",   "Practice can improve your English."),
    W("create",   "v.",    "创造；创作",   "We create something new."),
    W("learn",    "v.",    "学习；学会",   "I learn a new word today."),
    W("brave",    "adj.",  "勇敢的",       "The brave child tries again."),
    W("calm",     "adj.",  "平静的",       "Stay calm and take a breath."),
    W("dream",    "n./v.", "梦想；做梦",   "Her dream is to see the world."),
    W("enjoy",    "v.",    "享受；喜欢",   "We enjoy reading together."),
    W("friend",   "n.",    "朋友",         "A good friend listens to you."),
    W("grow",     "v.",    "成长；生长",   "Small plants grow in the sun."),
    W("happy",    "adj.",  "快乐的",       "I feel happy today."),
    W("kind",     "adj.",  "友善的",       "Be kind to other people."),
    W("listen",   "v.",    "倾听",         "Listen to the teacher."),
    W("practice", "n./v.", "练习",         "Practice makes the task easier."),
    W("quiet",    "adj.",  "安静的",       "The room is quiet at night."),
    W("remember", "v.",    "记住；想起",   "Remember to bring your book."),
    W("simple",   "adj.",  "简单的",       "The answer is simple."),
    W("strong",   "adj.",  "强壮的",       "A strong bridge crosses the river."),
    W("wonder",   "v./n.", "想知道；惊叹", "I wonder what happens next."),

    W("arrive",   "v.",    "到达",         "We arrive at school at eight."),
    W("ask",      "v.",    "询问；请求",   "Ask for help when you need it."),
    W("begin",    "v.",    "开始",         "The lesson begins now."),
    W("choose",   "v.",    "选择",         "Choose the answer you know."),
    W("close",    "v.",    "关闭",         "Please close the door."),
    W("cook",     "v.",    "烹饪",         "We cook dinner at home."),
    W("drink",    "v./n.", "喝；饮料",     "Drink some water after exercise."),
    W("drive",    "v.",    "驾驶",         "My father can drive a car."),
    W("eat",      "v.",    "吃",           "We eat lunch together."),
    W("finish",   "v.",    "完成",         "Finish your work before play."),
    W("help",     "v./n.", "帮助",         "Can you help me with this box?"),
    W("open",     "v./adj.", "打开；开放的", "Open the book to page ten."),
    W("read",     "v.",    "阅读",         "Read the sentence aloud."),
    W("speak",    "v.",    "说；讲",       "Please speak slowly."),
    W("start",    "v./n.", "开始",         "Start with the first question."),
    W("study",    "v./n.", "学习；研究",   "They study English every day."),
    W("walk",     "v./n.", "步行；散步",   "I walk to the park."),
    W("wash",     "v.",    "清洗",         "Wash your hands before dinner."),
    W("watch",    "v./n.", "观看；手表",   "We watch a short film."),
    W("write",    "v.",    "写",           "Write your name here."),

    W("family",   "n.",    "家庭；家人",   "My family eats dinner together."),
    W("mother",   "n.",    "母亲",         "My mother likes flowers."),
    W("father",   "n.",    "父亲",         "Her father reads every morning."),
    W("sister",   "n.",    "姐妹",         "My sister is a student."),
    W("brother",  "n.",    "兄弟",         "His brother plays football."),
    W("child",    "n.",    "孩子",         "The child draws a bear."),
    W("school",   "n.",    "学校",         "Our school has a small garden."),
    W("teacher",  "n.",    "老师",         "The teacher answers our questions."),
    W("student",  "n.",    "学生",         "Every student has a book."),
    W("house",    "n.",    "房子",         "Their house is near the river."),
    W("room",     "n.",    "房间",         "This room has two windows."),
    W("table",    "n.",    "桌子",         "The cup is on the table."),
    W("chair",    "n.",    "椅子",         "Please sit on this chair."),
    W("door",     "n.",    "门",           "Someone is at the door."),
    W("window",   "n.",    "窗户",         "Open the window for fresh air."),
    W("food",     "n.",    "食物",         "Fresh food tastes good."),
    W("water",    "n.",    "水",           "The glass is full of water."),
    W("morning",  "n.",    "早晨",         "I study in the morning."),
    W("evening",  "n.",    "傍晚；晚上",   "We take a walk in the evening."),
    W("today",    "n./adv.", "今天",        "Today is a good day to begin."),

    W("animal",   "n.",    "动物",         "Every animal needs water."),
    W("bird",     "n.",    "鸟",           "A small bird sits in the tree."),
    W("cat",      "n.",    "猫",           "The cat sleeps on the chair."),
    W("dog",      "n.",    "狗",           "The dog waits by the door."),
    W("flower",   "n.",    "花",           "This flower grows in spring."),
    W("garden",   "n.",    "花园",         "We grow vegetables in the garden."),
    W("river",    "n.",    "河流",         "The river runs past the town."),
    W("mountain", "n.",    "山",           "Snow covers the mountain."),
    W("rain",     "n./v.", "雨；下雨",     "The rain stops in the afternoon."),
    W("sun",      "n.",    "太阳",         "The sun is warm today."),
    W("moon",     "n.",    "月亮",         "The moon looks bright tonight."),
    W("sky",      "n.",    "天空",         "The sky is clear and blue."),
    W("spring",   "n.",    "春天",         "Flowers open in spring."),
    W("summer",   "n.",    "夏天",         "We swim in summer."),
    W("autumn",   "n.",    "秋天",         "Leaves change color in autumn."),
    W("winter",   "n.",    "冬天",         "Winter nights are long."),
    W("early",    "adj./adv.", "早的；早地", "She gets up early."),
    W("late",     "adj./adv.", "晚的；迟到", "Do not be late for class."),
    W("always",   "adv.",   "总是",         "He always keeps his word."),
    W("sometimes", "adv.",  "有时",         "Sometimes we learn from mistakes."),

    W("active",   "adj.",  "活跃的；积极的", "She is active in class."),
    W("careful",  "adj.",  "仔细的；小心的", "Be careful with the hot cup."),
    W("clear",    "adj.",  "清楚的；晴朗的", "Your answer is clear."),
    W("difficult", "adj.", "困难的",         "The task looks difficult at first."),
    W("easy",     "adj.",  "容易的",         "This question is easy."),
    W("excited",  "adj.",  "兴奋的",         "The children are excited about the trip."),
    W("gentle",   "adj.",  "温和的；轻柔的", "Use a gentle voice."),
    W("honest",   "adj.",  "诚实的",         "An honest answer builds trust."),
    W("important", "adj.", "重要的",         "Sleep is important for health."),
    W("lucky",    "adj.",  "幸运的",         "We are lucky to have good friends."),
    W("ready",    "adj.",  "准备好的",       "I am ready for the test."),
    W("safe",     "adj.",  "安全的",         "Keep your work in a safe place."),
    W("tired",    "adj.",  "疲倦的",         "I feel tired after the long walk."),
    W("useful",   "adj.",  "有用的",         "This small tool is useful."),
    W("warm",     "adj.",  "温暖的",         "The room is warm and quiet."),
    W("young",    "adj.",  "年轻的；年幼的", "The young tree needs water."),
    W("answer",   "n./v.", "答案；回答",     "Think before you answer."),
    W("question", "n./v.", "问题；提问",     "Ask one clear question."),
    W("change",   "n./v.", "改变；变化",     "Small steps can change a habit."),
    W("future",   "n.",    "未来",           "Learning opens doors to the future."),
};

_Static_assert(sizeof(WORDS) / sizeof(WORDS[0]) == WORD_BEAR_WORD_COUNT,
               "word bank size must match progress model");

const word_bear_word_t *word_bear_word_at(int index)
{
    if (index < 0 || index >= WORD_BEAR_WORD_COUNT) return NULL;
    return &WORDS[index];
}
